# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Execute & Push

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4
        pip install requests
        pip install lxml
    - name: ls
      run: |
        ls -1 ./python
    - name: Execute Python
      run: |
        while read line
        do
          python3 "./python/$line" > "./api/${line%.*}.txt"
        done < ./api_list.txt
    - name: Comapre and Push to API
      run: |
        git diff –exit-code
        echo $?
        if [[ $? -eq 1 ]]; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Push result to API"
          git push
        fi
