# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Execute & Push

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4
        pip install requests
    - name: Execute top_rank.py
      run: |
        echo $(ls -1 ./python/) > ./api/api_list.txt
        while read line
        do
          echo $(python3 ./python/$list) > ./api/${list%.*}
        done < ./api/api_list.txt
    - name: Push to API
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Push result to API"
        git push
