# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: get_tag_xml.py

on:
  push:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4
        pip install requests
        pip install lxml
    - name: Execute Python
      run: |
        python3 "./python/get_tag_xml.py" > "./api/get_tag.xml"
    - name: Comapre and Push to API
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Push get_tag.xml to API"
        git diff --exit-code
        echo $?
        if [ $(test -z "$(git status -s)") -eq 1 ]; then
          echo 'Some files are different'
          git push
        else
          echo 'Nothing to push'
        fi
